---
- name: Install python before anything else.
  raw: sudo apt install -y python

- name: Wait for automatic system updates
  become: yes
  become_user: root
  shell:     while sudo fuser /var/lib/dpkg/lock >/dev/null 2>&1; do sleep 1; done;

- name: Update and upgrade apt packages
  become_user: root
  become: True
  apt:
    upgrade: 'yes'
    update_cache: yes
...
